iotData/urls.py
from django.urls import path
from . import views
app_name = 'iotData'
urlpatterns = [
    path('test1/',views.test1, name="test1"),
    path('test2/',views.test2, name="test2"),
    path('add_sensor/',views.add_sensor,name="add_sensor"),
    path('main_page/',views.main_page,name="main_page"),#main page being used to add sensors
    path('home_data/',views.home_data,name = "home_data"),
    #path('graph/<int:sensor_id>/',views.get_graph_reading,name="graph"),
    path('graph/<int:sensor_id>',views.get_graph_reading, name="graph"),

]

water/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('iotData.urls')),

]
if settings.DEBUG: #Not for production code
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

iotData/models.py
from django.db import models
class Sensor(models.Model):
    url = models.CharField(null = True,max_length=250,blank=True)#key
    location_name = models.CharField(null = True,max_length=250,blank=True)
    active = models.BooleanField(default= False)
    channel = models.CharField(null= True, blank= True, max_length= 130)
    def __str__(self):
        return "Sensor: " + self.location_name
class Reading(models.Model):
    sensor = models.ForeignKey(Sensor,on_delete= models.CASCADE, related_name="read")
    field1 = models.FloatField(default= 0)
    field2 = models.FloatField(default= 0)
    field3 = models.FloatField(default= 0)
    field4 = models.FloatField(default= 0)
    field5 = models.FloatField(default= 0)
    wqi = models.FloatField(default= 0)
    time = models.DateTimeField(auto_now_add= True)
    def __str__(self):
        return "Reading from " + self.sensor.location_name

iotData/views.py
from django.shortcuts import render, redirect
import pusher
from django.http import HttpResponse
from .models import Sensor, Reading
from .tasks import my_reading_feed
pusher_client = pusher.Pusher(
  app_id='955817',
  key='d81c82457c99baa54a66',
  secret='da7d1eb8b0261474d8aa',
  cluster='ap2',
  ssl=True
)
def test1(request):
    global pusher_client
    if 'test1' in request.POST:
        val =request.POST['val']
        print(val)
        pusher_client.trigger('my-channel1', 'my-event', {'message': str(val)})#let us map channel id with sensor id
    return render(request,'test1.html')
def test2(request):
    return render(request,'test2.html')
def main_page(request):
    return render(request,'main_page.html')
def add_sensor(request):
    if 'add' in request.POST:
        url = request.POST['url']
        location = request.POST['location']
        my_sensor = Sensor(url = url,location_name = location,active = True)
        my_sensor.save()
        my_sensor.channel = 'my-channel' + str(my_sensor.id)
        my_sensor.save()
        my_reading_feed(my_sensor.id,repeat=1,repeat_until=None)
        return render(request,'main_page.html')
    return render(request,'main_page.html')
def home_data(request):
    all_sensor = Sensor.objects.all()
    return render(request,'home_data.html',{'all_sensor':all_sensor})
def get_graph_reading(request,sensor_id):
    sen = Sensor.objects.get(id = sensor_id)
    all_reading = Reading.objects.filter(sensor = sen).order_by('-pk')[:50]
    coordinates = []
    for reading in all_reading:
        my_date_time = ""
        x = reading.time 
        print(x)
        my_date = str(x.date())
        temp = str(x.time())
        (my_time,y) = temp.split('.')
        my_date_time = my_date + " " + my_time
        print(my_date_time)
        print(reading.field1)
        coordinates.append({'date_time':my_date_time,'field':reading.wqi})
    print(coordinates)
    return render(request,'graph.html',{'coordinates':coordinates})

# Create your views here.

templates/graph.html
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.3.0/Chart.bundle.js"></script>
<div class="container">
  <canvas id="examChart"></canvas>
</div>
<script>
    var ctx = document.getElementById("examChart").getContext("2d");

var myChart = new Chart(ctx, {
  type: 'line',
  data: {
    labels: [
    {% for x in coordinates %}
    new Date("{{x.date_time}}").toLocaleString(), 
    {% endfor %}
    ],
    datasets: [{
      label: 'Time vs Water Quality Index',
      data: [
      {% for x in coordinates %}
          {
          t: new Date("{{x.date_time}}"),
          y: {{x.field}}
        },
        {% endfor %}
      ],
      backgroundColor: [
        'rgba(255, 99, 132, 0.2)',
        'rgba(54, 162, 235, 0.2)',
        'rgba(255, 206, 86, 0.2)',
        'rgba(75, 192, 192, 0.2)',
        'rgba(153, 102, 255, 0.2)',
        'rgba(255, 159, 64, 0.2)'
      ],
      borderColor: [
        'rgba(255,99,132,1)',
        'rgba(54, 162, 235, 1)',
        'rgba(255, 206, 86, 1)',
        'rgba(75, 192, 192, 1)',
        'rgba(153, 102, 255, 1)',
        'rgba(255, 159, 64, 1)'
      ],
      borderWidth: 1
    }]
  }
});
</script>
    

templates/home_data.html
<!DOCTYPE html>
<head>
  <title>Home Data</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
  <style>
    .bgcol {
      background: #1e6cafff;
    }
    .f {
      font-size: 18px;
    }
  </style>
  <script src="https://js.pusher.com/5.1/pusher.min.js"></script>
  <script>

    // Enable pusher logging - don't include this in production
    Pusher.logToConsole = true;

    var pusher = new Pusher('d81c82457c99baa54a66', {
      cluster: 'ap2',
      forceTLS: true
    });
    {% for sensor in all_sensor %}
    var channel = pusher.subscribe('{{sensor.channel}}');
    channel.bind('my-event', function(data) {
      div = document.getElementById("my_div");
      field1 = document.getElementById("nr{{sensor.id}}")
      field2 = document.getElementById("temp{{sensor.id}}")
      field4 = document.getElementById("tds{{sensor.id}}")
      field3 = document.getElementById("turbidity{{sensor.id}}")
      field5 = document.getElementById("pH{{sensor.id}}")
      wqi = document.getElementById('wqi{{sensor.id}}')
      date = document.getElementById('fetch{{sensor.id}}')
      field1.textContent = data['NOx']
      field2.textContent = data['temp']
      field3.textContent = data['turbidity']
      field4.textContent = data['TDS'] 
      field5.textContent = data['pH']
      date.textContent = data['fetched']
      wqi.textContent = data['wqi']
      div.innerHTML += JSON.stringify(data);
    });
    {% endfor %}
  </script>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body style="text-align: center;background-color: #1e6cafff;">
  <div class="text-center" style="color: white;padding:10vh">
    <a class="btn-success btn-lg btn text-center" href="/main_page/">Add New Sensor</a>
    &nbsp;
    <a class="btn-danger btn-lg btn text-center">View Data</a>
 </div>

  <h1 class="text-center" style="color:yellow">Water Quality Test</h1>
  <br/>
  <br/>
  <!-- <form class="container">
    <!-- <h1>Aryan</h1>
      <div class="form-row justify-content-center">
          <div class="form-group col-md-3">
              <div class="input-group mx-auto mb-3">
                  <div class="input-group-prepend">
                      <button class="btn btn-primary" type="submit" name="action" value="<"><span class="ti-arrow-circle-left"></span></button>
                  </div>
                  <input class="form-control" type="text" size="2" name="listeanzahl" value="10" style="text-align:center">
                  <div class="input-group-append">
                      <button class="btn btn-primary" type="submit" name="action" value=">"><span class="ti-arrow-circle-right"></span></button>
                  </div>
              </div>
          </div>
      </div> -->
  
      <!-- <div class="form-row">
          <div class="form-group col-md-3 mx-auto">
              <div class="input-group mb-3">
                  <div class="input-group-prepend">
                      <button class="btn btn-primary" type="submit" name="action" value="<"><span class="ti-arrow-circle-left"></span></button>
                  </div>
                  <input class="form-control" type="text" size="2" name="listeanzahl" value="10" style="text-align:center">
                  <div class="input-group-append">
                      <button class="btn btn-primary" type="submit" name="action" value=">"><span class="ti-arrow-circle-right"></span></button>
                  </div>
              </div>
          </div>
      </div> -->
<!--
      <div class="form-row">
          <div class="input-group input-group-lg col-md-3 mx-auto">
              <input type="text" class="form-control" placeholder="Your Amount" aria-describedby="basic-addon1">
          </div>
      </div>
      <div class="form-row">
          <div class="input-group input-group-lg col-md-3 mx-auto">
              <input type="text" class="form-control" placeholder="Your Amount" aria-describedby="basic-addon1">
          </div>
      </div>
      <div class="form-row">
        <h1 class="f">TDS Level</h1>
          <div class="input-group input-group-lg col-md-3 mx-auto">
              <input type="text" class="form-control" placeholder="TDS Level" aria-describedby="basic-addon1">
          </div>
      </div>
  
  </form> -->
  <br/><br/><br/>
  <div class="table-responsive">
  <table class="table table-hover" style="border: 3px black solid;background: white;">
      <tr>
      <th>Location</th>
      <th>Nitrate</th>
      <th>Temperature</th>
      <th>Total Dissolved Solid</th>
      <th>Turbidity</th>
      <th>pH</th>
      <th>WQI</th>
      <th>Activity</th>
      <th>Last Fetched</th>
    </tr>
    
    {% for sensor in all_sensor %}
        <tr>
        <td><a href="/graph/{{sensor.id}}">{{sensor.location_name}}</a></td>
        <td id="nr{{sensor.id}}"></td>
        <td id="temp{{sensor.id}}"></td>
        <td id="tds{{sensor.id}}"></td>
        <td id="turbidity{{sensor.id}}"></td>
        
        <td id="pH{{sensor.id}}"></td>
        <td id="wqi{{sensor.id}}"></td>
        <td id="activity{{sensor.id}}">True</td>
        <td id="fetch{{sensor.id}}">Last Fetched</td>
        </tr>
    {% endfor %}
        
  </table>
</div>
</body>

templates/main_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">
    <title>Water Quality Test</title>
</head>
<body>
<div class="min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
    <div class="max-w-md w-full">
        <div>
            <img class="mx-auto h-12 w-auto" src="https://tailwindui.com/img/logos/workflow-mark-on-white.svg" alt="Workflow">
            <h2 class="mt-6 text-center text-3xl leading-9 font-extrabold text-gray-900">
              Sign in to your sensor
            </h2>
          </div>
      <form class="mt-8" action="{% url 'iotData:add_sensor' %}" method="POST">
        <h1 style="display:none">{% csrf_token %}</h1>
        <div class="rounded-md shadow-sm">
          <div>
            <input aria-label="url" type="text" name="url" placeholder="API Key of Sensor" required class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:shadow-outline-blue focus:border-blue-300 focus:z-10 sm:text-sm sm:leading-5">
          </div>
          <br/>
          <div class="-mt-px">
            <input aria-label="location" type="text" name="location" placeholder="Location" required class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-b-md focus:outline-none focus:shadow-outline-blue focus:border-blue-300 focus:z-10 sm:text-sm sm:leading-5">
          </div>
        </div>
  
        <div class="mt-6">
          <button name="add" type="submit" class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm leading-5 font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-500 focus:outline-none focus:border-indigo-700 focus:shadow-outline-indigo active:bg-indigo-700 transition duration-150 ease-in-out">
            Submit
          </button>
        </div>
      </form>
    </div>
  </div>
</body>
</html>    

templates/test1.html
<form action="{% url 'iotData:test1' %}" method="POST">
    {% csrf_token %}
<input type="text" name="val" placeholder="value">
<button name="test1">SUBMIT</button>
</form>

templates/test2.html
<!DOCTYPE html>
<head>
  <title>Pusher Test</title>
  <script src="https://js.pusher.com/5.1/pusher.min.js"></script>
  <script>

    // Enable pusher logging - don't include this in production
    Pusher.logToConsole = true;

    var pusher = new Pusher('d81c82457c99baa54a66', {
      cluster: 'ap2',
      forceTLS: true
    });

    var channel = pusher.subscribe('my-channel1');
    channel.bind('my-event', function(data) {
      div = document.getElementById("my_div");
      div.innerHTML = data.message;
    });
  </script>
</head>
<body>
  <div id="my_div">Hello</div>
  <h1>Pusher Test</h1>
  <p>
    Try publishing an event to channel <code>my-channel</code>
    with event name <code>my-event</code>.
  </p>
</body>